destination: ./_site
source:      ./www
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
# JRuby-specific info here; goes into the "site" jekyll variable
release:
  url: /2015/01/20/jruby-9-0-0-0-pre1.html
  version: 9.0.0.0.pre1
  tar: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby-bin-9.0.0.0.pre1.tar.gz
  zip: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby-bin-9.0.0.0.pre1.zip
  exe: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby_windows_9_0_0_0_pre1.exe
  exe64: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby_windows_x64_9_0_0_0_pre1.exe
  exejre: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby_windowsjre_9_0_0_0_pre1.exe
  exejre64: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/jruby_windows_x64_jre_9_0_0_0_pre1.exe
  dmg: https://s3.amazonaws.com/jruby.org/downloads/9.0.0.0.pre1/JRuby-9.0.0.0.pre1.dmg
urls:
  s3: https://s3.amazonaws.com/jruby.org/downloads
  tryjruby: https://s3.amazonaws.com/jruby.org/tryjruby
  bugs: http://github.com/jruby/jruby/issues
  jira: http://jira.codehaus.org/browse/JRUBY
  wiki: http://wiki.jruby.org/
  lists: http://wiki.jruby.org/MailingLists
  github: https://github.com/jruby/jruby
team_email: team@jruby.org
domain: www.jruby.org
